//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public int Disease_ID { get; set; }
        public string Hospital_Name { get; set; }
        public int ProductID { get; set; }
        public string DiseaseName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
